apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.metadata.name }}
  labels:
    app: {{ .Values.metadata.labels.app }}
spec:
  template:
    metadata:
      labels:
        job-name: {{ .Values.metadata.name }}  
    spec:
      containers:
        - name: {{ .Values.Container.Name }}
          image: {{ .Values.Container.Image }}
          envFrom:
            - secretRef:
                name: cve-processor-secrets
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1"        
      imagePullSecrets:
        - name: docker-creds
      restartPolicy: OnFailure
  backoffLimit: 4