apiVersion: v1
kind: ServiceAccount
metadata:
  name: webapp-cve-processor-sa
  namespace: webapp-cve-processor
  automountServiceAccountToken: false  # Disable auto-mounting if not interacting with the k8s API